
sudo: required
dist: trusty
language: cpp

before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq libsdl1.2-dev libsdl-image1.2-dev libpcap0.8-dev libcurl4-openssl-dev build-essential autoconf automake autotools-dev libcrypto++-dev

install: true

script: ./autogen.sh && ./configure && make

